### ISSUE TITLE
(JS-0750) Prefer not to use words image, photo in image alt content

### ISSUE THREAD

**Issue by sasicodes** [lenstube-xyz/lenstube#365]
## Description
Enforce img alt attribute does not contain the word image, picture, or photo. Screenreaders already announce img elements as an image. There is no need to use words such as image, photo, and/or picture.

## Occurrences
There are 12 occurrences of this issue in the repository.

See all occurrences on DeepSource &rarr; [deepsource.io/gh/lenstube-xyz/lenstube/issue/JS-0750/occurrences/](https://deepsource.io/gh/lenstube-xyz/lenstube/issue/JS-0750/occurrences/)

**Comment by zt4ff** [comment]
@sasicodes 

Can you assign this to me, please?

**Comment by zt4ff** [comment]
@sasicodes 
I made a new PR removing all "picture" text in the image alt attribute to stop redundancy since Deepsource recommended that screen readers would mention "image" after the `alt`

But I tested it with Screen Reader from Google: https://chrome.google.com/webstore/detail/screen-reader/kgejglhpjiefppelpmljglcjbhoiplfn/related?hl=en and it's not mentioning "image". 

Should I just change the alt to "channel avatar" for the most part of leave it as it is?

**Comment by sasicodes** [comment]
@zt4ff we can add (channel.handle) in possible places.

**Comment by zt4ff** [comment]
@sasicodes updated

**Comment by sasicodes** [comment]
@zt4ff I mean {channel.handle} dynamic text from api

**Comment by zt4ff** [comment]
@sasicodes oops!
I got it now

**Comment by zt4ff** [comment]
@sasicodes 
It's updated now
I made new push
